[tool.pylance]
typeCheckingMode = "basic"
reportMissingImports = "none"
reportOptionalMemberAccess = "none"
reportOptionalSubscript = "none"
reportOptionalCall = "none"
reportArgumentType = "warning"
reportAssignmentType = "warning"
reportAttributeAccessIssue = "none"
reportReturnType = "warning"
reportCallIssue = "warning"
reportGeneralTypeIssues = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownMemberType = "none"
reportMissingTypeStubs = "none"
reportImportCycles = "none"
reportUnusedImport = "none"
reportUnusedClass = "none"
reportUnusedFunction = "none"
reportUnusedVariable = "none"
reportDuplicateImport = "none"
reportWildcardImportFromLibrary = "none"
reportOptionalIterable = "none"
reportOptionalContextManager = "none"
reportOptionalOperand = "none"
reportTypedDictNotRequiredAccess = "none"
reportPrivateImportUsage = "none"
reportConstantRedefinition = "none"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportOverlappingOverloads = "none"
reportUninitializedInstanceVariable = "none"
reportInvalidStringEscapeSequence = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportInvalidTypeVarUse = "none"
reportCallInDefaultInitializer = "none"
reportUnnecessaryIsInstance = "none"
reportUnnecessaryCast = "none"
reportUnnecessaryComparison = "none"
reportAssertAlwaysTrue = "none"
reportSelfClsParameterName = "none"
reportImplicitStringConcatenation = "none"
reportUndefinedVariable = "error"
reportUnboundVariable = "error"
reportInvalidStubStatement = "none"
reportIncompleteStub = "none"
reportUnsupportedDunderAll = "none"
reportUnusedCoroutine = "none"
reportFunctionMemberAccess = "none"
reportIncompatibleDefaultValue = "none"
reportNamedTupleNotRequiredAccess = "none"

[tool.pyright]
typeCheckingMode = "basic"
reportMissingImports = false
reportOptionalMemberAccess = false
reportOptionalSubscript = false
reportOptionalCall = false
reportGeneralTypeIssues = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false
reportImportCycles = false
reportUnusedImport = false
reportUnusedClass = false
reportUnusedFunction = false
reportUnusedVariable = false
reportDuplicateImport = false
reportWildcardImportFromLibrary = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportTypedDictNotRequiredAccess = false
reportPrivateImportUsage = false
reportConstantRedefinition = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false
reportOverlappingOverloads = false
reportUninitializedInstanceVariable = false
reportInvalidStringEscapeSequence = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportInvalidTypeVarUse = false
reportCallInDefaultInitializer = false
reportUnnecessaryIsInstance = false
reportUnnecessaryCast = false
reportUnnecessaryComparison = false
reportAssertAlwaysTrue = false
reportSelfClsParameterName = false
reportImplicitStringConcatenation = false
reportUndefinedVariable = true
reportUnboundVariable = true
reportInvalidStubStatement = false
reportIncompleteStub = false
reportUnsupportedDunderAll = false
reportUnusedCoroutine = false
reportFunctionMemberAccess = false
reportIncompatibleDefaultValue = false
reportNamedTupleNotRequiredAccess = false
