name: "AIMER - Deploy"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: "Build package"
        run: |
          python -m build

      - name: "Create Release Notes"
        run: |
          echo "# AIMER Release ${{ github.ref_name }}" > release_notes.md
          echo "" >> release_notes.md
          echo "Nouvelle version d'AIMER disponible !" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Changements" >> release_notes.md
          git log --oneline --since="1 month ago" >> release_notes.md

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "AIMER ${{ github.ref_name }}"
          body_path: release_notes.md
          draft: false
          prerelease: false
