name: Deploy AIMER PRO - Interface Web Unifiée

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_web.txt
    
    - name: Create documentation
      run: |
        mkdir -p docs
        # Copie de l'interface web pour demo en ligne
        cp ui/web_interface/templates/index.html docs/
        echo "# AIMER PRO - Interface Web" > docs/README.md
        echo "Interface de démonstration AIMER PRO" >> docs/README.md
        echo "" >> docs/README.md
        echo "## Fonctionnalités" >> docs/README.md
        echo "- Détection d'objets COCO intelligente" >> docs/README.md
        echo "- Interface webcam temps réel" >> docs/README.md
        echo "- Upload et analyse d'images" >> docs/README.md
        echo "- Analyse de vidéos YouTube" >> docs/README.md
        echo "" >> docs/README.md
        echo "Version unifiée et propre - Plus de doublons !" >> docs/README.md
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
