name: "AIMER - Tests"

on:
  push:
    branches: [main, dev, alpha]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  test:
    name: "Run Tests"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name:  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements_security.txt

      - name:  Run basic tests
        run: |
          python -c "import sys; print(f'Python {sys.version}')"
          python -c "import platform; print(f'Platform: {platform.system()}')"

      - name: ✅ Test imports
        run: |
          python -c "import pathlib; print('✅ pathlib OK')"
          python -c "import subprocess; print('✅ subprocess OK')"
          python -c "import json; print('✅ json OK')"

      - name: 🔍 Lint check
        run: |
          python -m py_compile *.py || echo "⚠️ Some Python files have syntax errors"

      - name: 📊 Test report
        run: |
          echo " Tests completed for Python ${{ matrix.python-version }} on ${{ matrix.os }}"
